### ISSUE TITLE
How to delete an article?

### ISSUE THREAD

**Issue by HuMonkey** [Requarks/wiki#102]

**Comment by NGPixel** [comment]
You can't from the UI right now, which is by design. Deleting content is dangerous unless there's a feature to revert and strict permissions as to how this is handled, which is not the case right now.

This feature will be added in the future, but in the meantime, you must delete the files manually in the `/repo` folder.

**Comment by Darv72** [comment]
I have a follow up to this question as I am trying to delete some test content I added to our wiki.  I have deleted the relevant file from the repo however the deleted page is still listed in the navigation pane for All Pages.  Is there something I need to do in addition to deleting the page from the repo?

**Comment by NGPixel** [comment]
1) Delete the file in the repo
2) Restart Wiki.js (`node wiki restart`)
