### ISSUE TITLE
Add Untracked Changes adds whole project in git

### ISSUE THREAD

**Issue by ayZagen** [Requarks/wiki#1026]
**Describe the bug**
`Add Untracked Changes` adds all project files to the git instead of data.

**To Reproduce**
1. Go to Storage > Git
2. Select `Push to Target` as sync direction
3. Apply
3. Scroll down and click `Add Untracked Changes`
4. Click `Force Sync`
5. Check git repository you will see whole project there

**Expected behavior**
Only docs should be added.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.0-beta.275
 - Database engine: postgres 9.6

**Comment by NGPixel** [comment]
This is because you've either you've set the `Local Repository Path` option to the root of the app or you cloned the project into a directory and you're running the app directly from that directory. You cannot have a git repo within a git repo. So set the local repository path somewhere outside of the project root.

**Comment by ayZagen** [comment]
That makes sense. Thank you
