### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1051]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04]
Wiki.js version: [e.g. 2.0.0-beta.303]
Database engine: [mysql 8]

Is there a way to hide the Local icon for the Login screen. We will be using google login for accessing the site.
![image](https://user-images.githubusercontent.com/46513658/65301552-af598380-db95-11e9-8769-8009646b8d07.png)

**Comment by ethanmdavidson** [comment]
According to the docs, the Local auth method cannot currently be disabled: https://docs.requarks.io/en/auth/local. I believe this is because the default admin user is created with local auth, and if local auth became disabled you could potentially lock yourself out of your instance.

You may be interested in [this feature request](https://wiki.js.org/feedback/p/change-order-of-login-options) to allow changing the priority of the login options. This would allow you to set Google as the default.

**Comment by NGPixel** [comment]
You cannot disable the local authentication as this is required for the root administrator. Add your vote to the feature request linked above which should address your issue.
