### ISSUE TITLE
401 Error with NGINX Basic Authentication

### ISSUE THREAD

**Issue by hided62** [requarks/wiki#1095]
**Describe the bug**
I exposed wiki.js through nginx's reverse proxy.

And because of some requirements, when I enabled the basic authentication feature in nginx, Wiki.js caused an infinite 401 error, requiring Basic login.

This Basic login window continued even after entering the correct username and password.

The problem does not occur when viewing the login page or document, and only when trying to create a new document.

Also, this problem did not occur in Firefox.
Instead, when checking through the developer tools, 401 error occurs in graphql and `Network Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data` appears.

**To Reproduce**
1. Install wiki.js using Docker compose.
2. Enable proxy_pass in the Nginx configuration file and specify auth_basic, auth_basic_user_file.
3. Enter the correct username and password for Basic login and start the first setup of wiki.js.
4. Press the button to create the first document, the Basic login window appears with a 401 error.

**Expected behavior**
Should be able to edit the document normally

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04 + Docker
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: postgres 9.7
 - Web browser: Chrome 77

**Comment by NGPixel** [comment]
Why are you using HTTP basic auth instead of just using the built-in Wiki.js authentication?

**Comment by hided62** [comment]
I want to run the wiki completely private. In addition to some of the features available to users in the subdirectories of this domain, I have reverse proxyed them, and I plan to run these features privately as well.

Of course, it's fine that applying basic authentication only to subdirectories. But applying basic authentication throughout the domain wasn't bad either.

**Comment by NGPixel** [comment]
Why not make your wiki private instead?

https://docs.requarks.io/groups#private-wiki

**Comment by hided62** [comment]
As mentioned above, I think private-wiki is a good way. However, other services I run did not provide a way for proper ACLs other than basic authentication.

**Comment by hided62** [comment]
What I want to say is whether it is intended to get a 401 error on the path reported here. If so, I think I would change the access path of the service I provide.

**Comment by bramton** [comment]
I have the same issue. It is caused by the POST method to the graphql endpoint. The client side javascript will set its own Authorization header:
```javascript
// Inject authentication token
const jwtToken = Cookies.get('jwt')
if (jwtToken) {
    options.headers.Authorization = `Bearer ${jwtToken}`
}
````
Unfortunatly there doesn't seem to be a solution, also see this issue: https://github.com/portainer/portainer/issues/2809

**Comment by NGPixel** [comment]
For the same reason provided in the portainer issue, basic auth on top of Wiki.js will not be supported. Use the built-in authentication instead.

**Comment by pavbro** [comment]
It is a pity that you refuse to support Basic Auth. Hiding a door from a burglar is much safer than offering to break in. Many people will probably abandon this product for this reason, as I did. Too bad. I can't allow the chance for someone to try to hack your authorization on a service that contains sensitive information.

**Comment by NGPixel** [comment]
@pavbro Supporting Basic Auth is not trivial and it conflicts with the Authorization header used by the GraphQL API. So I'm not going to completely rewrite the API authentication just to be able to support an extremely weak auth protocol, which should not even be used nowadays. You can't have both auth methods using the same header at the same time, it's simply not possible.

If your argument relies on having Basic Auth to protect your wiki because the built-in auth is potentially not secure, I'm sorry but you're very misguided. It's so much easier and faster to break Basic Auth, not even close.

**Comment by NGPixel** [comment]
@HanseHouse Except using Basic Auth to protect your website is pointless in 2023 and definitely not "good practice". You're sending a password in cleartext _on every single request._

Use IP whitelisting instead if you need to restrict access to only a few users.

**Comment by HanseHouse** [comment]
> @HanseHouse Except using Basic Auth to protect your website is pointless in 2023 and definitely not "good practice". You're sending a password in cleartext _on every single request._
> 
> Use IP whitelisting instead if you need to restrict access to only a few users.

Thank you for your reply.

Basic Auth is transmitted in HTTP headers which are encrypted by TLS, so there is no cleartext-transmission. It has the same encryption-level as authentication cookies or tokens, which are also sent on every request. It's the lifetime that differs, Basic-Auth password and cookies are both stored in browser during the session, but cookies have a limited lifetime.
Basic Auth the way we want to use it should not replace the user-authentication of the web site, it's an additional measurement where man-in-the-middle attacks and intercepting communication are not relevant and thus lifetime is also irrelevant. It's to protect from 0days, almost every major non-authenticated attacks (Log4Shell, confluence etc) would not have been possible with protected routes.

We can't use IP whitelisting because we have no whitelist. We usually don't have fixed IPs on client side and especially not on mobile. Normally we use an IP-whitelist to disable Basic Auth for known sources.

I understand that it is not possible to implement in wiki.js because it conflicts in GraphQL and under no circumstances I would demand it :-)
I'm happy to put wiki.js behind a VPN, I just wanted to explain why people are using it.

**Comment by ksaadDE** [comment]
> Basic Auth to protect your website is pointless in 2023 and definitely not "good practice"

Basic Auth successfully stops attackers without credentials and prevents illegal crawling.  It has a nice support and can be activated EASILY in e.g. nginx. When used in combination with HTTPS, there is no "clear text" transmission of the b64 encoded username:pw. At best there is a UFW running or any other firewall that detects and blocks bruteforce attempts (in any situation it's very rare that passwords with > 128 chars are bruteforced over the network) 

> Use IP whitelisting instead if you need to restrict access to only a few users.

Which is not possible without static ips and ip-spoofing is more trivial than HTTP Auth attacks  ;) 

Supporting Basic Auth is a must-have OR any other possibility to lockdown the site to a "private mode" behind e.g. a reverse proxy, generally speaking.

**Comment by NGPixel** [comment]
@ksaadDE As I already mentioned, Basic Auth is not and will not be supported. It conflicts with the Authorization header. There are a myriad of alternatives you can use to secure your wiki, use them.

**Comment by ksaadDE** [comment]
> There are a myriad of alternatives you can use to secure your wiki, use them.

You mean your app  (Was it the GraphQL stuff?)  overwrites the Authorization header and such makes the use of HTTP Basic Auth impossible? Yes, but to fix this there are other Authorization headers or even GET parameters. 

HTTP Basic Auth is probably the only and most simple to use protection measure. You can surely recommend something that works better for an nginx reverse proxy, that is not IP-whitelisting (which is not better nor secure at all).

One solution to fix that could be using comma separated Authorization headers or a distinct header for the GraphQL stuff (which needs modification of GQL). Though this solution is rather hacky than supported (alone looking at the corresponding RFCs).

The HTTP Auth Digest Nginx Module (which uses the same header), is not that well developed compared to HTTP Basic Auth and has issues with reverse proxies: https://github.com/atomx/nginx-http-auth-digest/tree/master

I strongly suggest fixing the Authorization headers, so we all can use HTTP Basic Auth optionally or providing another alternative that hides the wiki from the public - putting it behind auth.

**Comment by NGPixel** [comment]
Sorry but this is a lot of nonsense. IP allowlisting is secure when your network edge is handling and filtering incoming packets correctly, and not even close to being on the same level as basic auth. 

I'm not interested into arguing the benefits of basic auth. **It will NOT be supported.** I'm not going to put time into implementing weak workarounds to handle basic auth in addition to a bearer token. If that doesn't work for you, then please use another wiki. Topic closed.
