### ISSUE TITLE
Installed but not working?

### ISSUE THREAD

**Issue by vlos** [Requarks/wiki#11]
I have installed the wiki and started it but can't seem to access it.

**Got the following WARNings during install.**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\vlos\WebstormP
rojects\Wiki.js\package.json'
npm WARN Wiki.js No description
npm WARN Wiki.js No repository field.
npm WARN Wiki.js No README data
npm WARN Wiki.js No license field.

Also mongoDB is running, which it doesn't say required to startup, though I seem to have gotten farther with it running. Not sure if I need to create initial repository or what? (I use mongo for homebrewery before wiki).

it did seem to prompt me for my GIT login, but the webpage just sits there? NOt sure if I need to create repository for wiki? Again it doesn't specify it in the install/run.

_Ok figured it out, Need to setup db directory._

So install/start instructions seem to be lacking.
https://docs.wiki.requarks.io/install

**Missing:**

- steps to start and configure MongoDB for Wiki

**Comment by NGPixel** [comment]
- The warnings during the npm install can safely be ignored.
- MongoDB is a requirement, which means it should be installed and running before attempting to install Wiki.js. Just like when you install Wordpress, it is expected that you have MySQL up and running. As for configuration, no further steps is required. As long as Wiki.js can connect to your MongoDB, it will create the DB and collections automatically the first time. If you installed MongoDB locally without changing any default settings, then you can simply point to `mongodb://localhost:27017/wiki` in your config.yml, which is the default value.
- It shouldn't prompt for your Git login. Otherwise it isn't configured properly. Have you entered your Git login and connection info into config.yml? Or set `git: false` if you don't want remote sync.
- If you can't access your wiki, it means there are errors that need to be fixed, which you can view by running `pm2 logs wiki`.

**Comment by vlos** [comment]
As mentioned I have it up and running at this point, I feel you need to work on the install documents to make it clear.

Also when you start the wiki you should display the active port it's listening on along with possibly the paths.  I have been playing around with different servers and such - trying to find something that suits me, so I don't remember these (or it just might be my age).

Lastly your markup/conversion is inconsistent.

For example when I enter in *test* if converts to it to italics

When I enter in **test** it converts to bold **test**.

When I enter in # Header it converts to a header which still includes the markup?!!?!>!?! WHY? you strip off the other markdown syntax, but leave the header syntax?????

**Comment by NGPixel** [comment]
Thanks for the suggestions. I'll see how I can simplify installation and configuration tasks even more.

As for markdown parsing, this is the default behavior. It relies on the markdown-it module for conversion, so it's pretty much standard. Which inconsistencies are you referring too? From your screenshots, it seems to point to the line breaks? A single line break doesn't actually produce a line break once converted, however I understand this can be confusing at first. Fortunately, this is a setting I can play with so I'll most likely add a setting to enable single line breaks in the next release.

**Comment by vlos** [comment]
The main inconsistency I am trying to show is the Header.

Where you have a (#) to indicate a header, it formats it as a header, but keeps the (#). Where as the (**) for bold is hidden, or (*) for italic is also hidden.

So it converts the markdown elements, but it shows/keeps the markdown syntax in other cases.

**Comment by NGPixel** [comment]
I see. It doesn't keep the markdown syntax at all. The # before the header is meant to be an anchor, which you can use to link directly to this section of the page. I look into using a more descriptive icon instead, like ⚓️
