### ISSUE TITLE
Table of contents links not working

### ISSUE THREAD

**Issue by carloposo** [Requarks/wiki#1127]
# Actual behavior
Clicking any of the automatically generated links in the Table of Contents does not result in the page to scroll down to the clicked Chapter.

### Expected behavior
The page goes down to the selected Chapter.

**Comment by NGPixel** [comment]
Fixed by 37ce116dd2bee0471650c335ffb3ccf84323e5b8

**Comment by GeorgeGedox** [comment]
Can anyone confirm this is indeed fixed in 2.5? Any link I click in the table of contents has broken javascript `TypeError: Target must be a Number/Selector/HTMLElement/VueComponent, received undefined instead.`. I don't know what to do and this is something that's quite essential of a wiki software.
