### ISSUE TITLE
Why is NPM Deprecated

### ISSUE THREAD

**Issue by machineghost** [Requarks/wiki#1128]
**Question**
NPM is the easiest way to install a package: `npm i package-name` ... it doesn't get any easier than that.

It's also the standard way that virtually every open source Javascript library on the planet is distributed ... even your's (evidently, at one point).

So it just seems super strange to read this library's docs and find (essentially) "yeah, we don't do the thing EVERYONE ELSE does: that's deprecated", with no explanation whatsoever of _why_ it's deprecated.  Even a sentence or two on that documentation page would be super helpful.

Just say something like "we hate the Node org" or "it's a hassle to package with NPM, but we will once 2.0 is done", or _whatever_ it may be ... but again, it's very off-putting when you're considering a new library, and they purposefully violate an "industry best practice" ... without any explanation of _why_.

**Comment by NGPixel** [comment]
First off, take a deep breath and calm your horses.

Wiki.js is **NOT a library or a package**, hence making no sense for it to be installed using this method, which is why it was deprecated in the first place and will not be re-introduced at any point in the future. Wiki.js will never be a dependency to another project. It's a standalone server, self-contained app, which just happens to run on Node.js.

You'll find that most major applications that are not libraries and run as node server do not use npm directly as an installer. Take Ghost for example, a popular blog platform. They did a "Ghost-CLI" which you can install via npm, from which can you then run to install Ghost itself.

I see no point in wasting development time on building a CLI that must have various implementations for all platforms simply to perform an installation that could be achieved by you running a very simple bash / terminal / powershell command instead.

**Comment by machineghost** [comment]
It's easy to read things into text that are not there, but  I ... and my horses ;) ... were perfectly calm.

I don't think it's an outrageous thing to ask that documentation include an answer to an obvious question.
