### ISSUE TITLE
Most Markdown sidebar tool icons disabled? (v2)

### ISSUE THREAD

**Issue by Codelica** [Requarks/wiki#1236]
**Question**
When editing a Markdown page, all of my sidebar tool icons (except "Insert Assets"), appear to be disabled / grey'd out.  Curious if I'm overlooking configuration to enable them or ?  Some appear to be useful features like adding links, etc.  

**Host Info (please complete the following information):**
Docker w/ Wiki.js version 2.0.1  Postgres 12.0

![wiki-markdown-icons](https://user-images.githubusercontent.com/386101/69173952-17f1ad80-0abe-11ea-8a2d-73eb2a1b0613.jpg)

**Comment by XerqJon** [comment]
@Codelica I think those just haven't finished development yet. If you're familiar with markdown, you can accomplish each of the functions manually. 

In addition to the ( ? ) help* button in the lower left of the editor which shows some examples of markdown syntax, you can also reference the [Wiki.JS docs entry on the Markdown editor ](https://docs.requarks.io/en/editors/markdown) which includes more useful examples and styling options. 

* there is a bug (now fixed, currently unreleased) that causes the help window to appear at the bottom of the page (you have to scroll) instead of bringing right to the front.

**Comment by Codelica** [comment]
Thanks! Yes, I'm familiar w/ the syntax.  Was mainly curious before trying to go live with this for our team -- who *love* buttons ;)  I'd like to keep everything in Markdown for the rest of us, but it seems the "Visual Editor" will be more attractive to them at this point.  Probably just old off for now.  Thanks for the info!

**Comment by NGPixel** [comment]
As @XerqJon mentionned. These are simply not working yet and will become available in upcoming builds.
