### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource 

### ISSUE THREAD

**Issue by AaronNGray** [Requarks/wiki#1315]
**Describe the bug**

Getting following in console :-

    Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:3000/js/setup.0f36c8857e987ef851bf.js' with computed SHA-256 integrity 'NGFLLru9lqVFcgJNnkPj+NWmN4EeXkNKgfaKvL4jgnM='. The resource has been blocked.

**To Reproduce**
Install :-
https://github.com/Requarks/wiki/releases/tag/2.0.12

following :-
https://docs.requarks.io/install/windows

**Expected behavior**
Setup on http://localhost:3000

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
Windows 10
 - Wiki.js version: [e.g. 2.0.1]
2.0.12
 - Database engine: [e.g. postgres 9.7, mysql 5.7]
PostgreSQL 10
**Additional context**

**Comment by NGPixel** [comment]
I just did a fresh install on Windows 10 following the exact instructions on https://docs.requarks.io/install/windows

Upon running `node server`, I get the the prompt to browse to localhost:3000:
```
2019-12-18T20:04:39.991Z [MASTER] info: =======================================
2019-12-18T20:04:39.994Z [MASTER] info: = Wiki.js 2.0.12 ======================
2019-12-18T20:04:39.994Z [MASTER] info: =======================================
2019-12-18T20:04:39.995Z [MASTER] info: Initializing...
2019-12-18T20:04:40.682Z [MASTER] info: Connecting to database...
2019-12-18T20:04:40.716Z [MASTER] info: Database Connection Successful [ OK ]
2019-12-18T20:04:41.111Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-12-18T20:04:41.112Z [MASTER] info: Starting setup wizard...
2019-12-18T20:04:41.586Z [MASTER] info: Starting HTTP server on port 3000...
2019-12-18T20:04:41.587Z [MASTER] info: HTTP Server on port: [ 3000 ]
2019-12-18T20:04:41.590Z [MASTER] info: HTTP Server: [ RUNNING ]
2019-12-18T20:04:41.591Z [MASTER] info: 🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
2019-12-18T20:04:41.591Z [MASTER] info:
2019-12-18T20:04:41.591Z [MASTER] info: Browse to http://localhost:3000/ to complete setup!
2019-12-18T20:04:41.591Z [MASTER] info:
2019-12-18T20:04:41.592Z [MASTER] info: 🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
```

In both Chrome Stable and MS Edge Beta, I get the following setup screen:
![image](https://user-images.githubusercontent.com/15522395/71119491-4a1f2980-21a8-11ea-9e88-a98b8e8d1ed0.png)

Which proves the current windows build works.

The integrity error means the js file is being altered somewhere along the road and doesn't match the signature it was built with, which is why the browser refuses to load it.

**Comment by AaronNGray** [comment]
Oh thanks for looking at it I will try again and report back.

**Comment by AaronNGray** [comment]
Okay its working now ! I will do diffs and work out what the difference was. Sorry for so much noise.

**Comment by AaronNGray** [comment]
I am getting one difference between WinZip and tar
```
diff -Nurd wikijs-working/node_modules/passport-twitch/.npmignore wikijs/node_modules/passport-twitch/.npmignore
--- wikijs-working/node_modules/passport-twitch/.npmignore      2019-11-23 21:49:35.000000000 +0000
+++ wikijs/node_modules/passport-twitch/.npmignore      2019-11-23 21:49:36.000000000 +0000
@@ -39,7 +39,8 @@
 .LSOverride

 # Icon must end with two \r
-Icon
+Icon
+

 # Thumbnails
 ._*
```

**Comment by 10093241** [comment]
> I am getting one difference between WinZip and tar
> 
> ```
> diff -Nurd wikijs-working/node_modules/passport-twitch/.npmignore wikijs/node_modules/passport-twitch/.npmignore
> --- wikijs-working/node_modules/passport-twitch/.npmignore      2019-11-23 21:49:35.000000000 +0000
> +++ wikijs/node_modules/passport-twitch/.npmignore      2019-11-23 21:49:36.000000000 +0000
> @@ -39,7 +39,8 @@
>  .LSOverride
> 
>  # Icon must end with two \r
> -Icon
> +Icon
> +
> 
>  # Thumbnails
>  ._*
> ```
> 
> but it should make no difference.
> 
> The only thing left is running it in PowerShell rather than CMD for the first time.

Hi, I had the same issue with u, the local:3000 is blank page , and  console showed that  'Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:3000/js/setup.0f36c8857e987ef851bf.js' with computed SHA-256 integrity 'NGFLLru9lqVFcgJNnkPj+NWmN4EeXkNKgfaKvL4jgnM='. The resource has been blocked.'

So could u tell me what the solution is.  by using 'tar' instead of 'WinZip'?
Many Thanks!
