### ISSUE TITLE
Login Flow for v.2

### ISSUE THREAD

**Issue by ilyamochalov** [Requarks/wiki#1331]
**Describe the bug**
If a user follows a link but is not logged in, it redirects the user to the front page after authenticating. Basically, the same thing that was implemented for v1 (https://github.com/Requarks/wiki/issues/141) previously, but is missing now

**To Reproduce**
1. Ensure you are logged out
2. Try to visit a specific page
3. You are redirected to the login page
4. Log in
5. You are redirected to the front/home page

**Expected behavior**
The user should be redirected back to the link/page they requested.

**Host Info (please complete the following information):**
 - OS: any
 - Wiki.js version: 2.0.12
 - Database engine: postgres 11

**Comment by zbal** [comment]
It'd be great to be able to define a default "landing" page per user, as opposed to only considering supporting the redirect to the page the user was on prior to the login. 

E.g. 

user | default landing | redirect to after login
----|----|----
user1 | none (default `/`) | previous page or `/` if no ACL to previous
user2 | `/some-page` | previous page or `/some-page` if no ACL to previous
user3 | `/other-page` | previous page or `/other-page` if no ACL to previous

If custom landing pages are unreachable due to ACL - keep the same behaviour as now --> redirect to `/login`.

Bonus: define landing page per group :) with precedence on the user specific landing (obviously more hassle handling multi-groups ...)

**Comment by NGPixel** [comment]
Fixed by ff5acba358fcdbc8c527527b20103c412e732320

@zbal Create a feature request for a group default landing on https://wiki.js.org/feedback
