### ISSUE TITLE
Can't connect wiki.js to PostgreSQL using docker-compose

### ISSUE THREAD

**Issue by paulhannes** [Requarks/wiki#1338]
### Actual behavior
I'm using the standard not-changed docker-compose.yml but i always get the following error:

`` error: Database Connection Error: EHOSTUNREACH 172.19.0.3:5432``

I tried it with mariadb and mysql but i got the same error, both container are in the same network. I also tried to use the config.yml and not the Environment Variables but it didn't work.

Does anyone know where to get more log of wiki.js or did anyone even had the same error?

### Expected behavior
well - that wiki.js would connect to PostgreSQL and everything would work fine.

This is my first issue on GitHub, please forgive my maybe non-professional issue.

Thank You!
Paul
[docker-compose.txt](https://github.com/Requarks/wiki/files/4006273/docker-compose.txt)

**Comment by NGPixel** [comment]
You're not using the standard "not-changed" docker-compose as there are many things wrong with your docker-compose file...

- You have both ENV variables and you map the config file. Use one or the other, not both at the same time.
- You're overriding the default network to use nginx_wiki.
- WIKI_ADMIN_EMAIL is not a valid variable and doesn't do anything.
- CONFIG_FILE is useless if you're defining the mapped volume at the exact same location.
- Avoid using passwords that starts with numbers when using the config.yml. They are incorrectly interpreted as integers instead of a string. Another option is to put quotes around them.

Refer to the provided Docker compose example in the docs, it's been verified to work:
https://docs.requarks.io/install/docker#using-docker-compose
