### ISSUE TITLE
links from All Pages list omit port number

### ISSUE THREAD

**Issue by EricFromCanada** [Requarks/wiki#134]
### Steps to reproduce the behavior
- host a wiki.js instance behind a port other than 80
- click a link in the All Pages view

### Actual behavior
- link goes to hostname/pagename, resulting in a connection error

### Expected behavior
- link preserves the port number by going to hostname:port/pagename

**Comment by NGPixel** [comment]
You must add the port to the `host` parameter in your config file.

e.g.:
```yaml
host: http://yoursite.com:3333
```

**Comment by EricFromCanada** [comment]
Really? Seems kind of redundant to have this in a config file. Also, the [docs](https://docs.requarks.io/wiki/install/configuration) don't mention this.
```
host: http://yoursite.com:8000
port: 8000
```

**Comment by NGPixel** [comment]
**They have different purposes.** Host is the base URL users actually use, while port is the what wiki.js listens to. If you're using a reverse proxy or load balancer in front of Wiki.js, the host and port values will be quite different.

For example, the documentation site is listening to port 3001, but users are actually going through port 443 because of the reverse proxy.

I added some info to the documentation.
