### ISSUE TITLE
links are broken when link address having a space

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#138]
### Actual behavior
Links are broken when link address having a space, such as [Link Text](Link Address).

### Expected behavior
Should be a link.

### Steps to reproduce the behavior

For example: [Link Text](Link Address) or the examples on https://note.fei-xing.com/playground

![wiki js-links](https://user-images.githubusercontent.com/10532949/27261445-bcc618ac-5475-11e7-8340-0f5c1d85adf0.png)

**Comment by NGPixel** [comment]
Spaces in URL are never valid and no pages in Wiki.js will ever contain spaces; they automatically converted to kebab-case syntax (e.g. `https guidelines` becomes `https-guidelines`).

If you're linking to an external link which has spaces (again, that should be avoided), you can simply replace the spaces with `%20` in the link portion.

**Comment by fireundubh** [comment]
> If you're linking to an external link which has spaces (again, that should be avoided), you can simply replace the spaces with %20 in the link portion.

Instead of marking this issue invalid, why don't you implement this with `encodeURI()`? This would keep the page source clear of ugly escape sequences, and you'd be able to have pages that have URLs that look like they have spaces. You'll note that modern browsers display URLs with spaces without escape sequences.

**Comment by NGPixel** [comment]
Because it's not valid Markdown. The [Commonmark spec](http://spec.commonmark.org/0.28/#links) specifically forbids spaces in URLs. The space is used to specify the link title in links and attributes in image links.

So either you escape the links yourself or you wait for wiki.js 2.1 which will offer non-markdown editors, allowing you to use spaces in links directly.

**Comment by fireundubh** [comment]
> Because it's not valid Markdown. The Commonmark spec specifically forbids spaces in URLs. 

So, how do you create subpages then?
