### ISSUE TITLE
Setting the site URL does not help with subfolder hosting using Nginx

### ISSUE THREAD

**Issue by RossComputerGuy** [Requarks/wiki#1417]
**Describe the bug**

**To Reproduce**
1. Setup Wiki.js
2. Setup nginx to host wiki.js on /wiki
3. Connect

**Expected behavior**
CSS and other resources to load

**Host Info (please complete the following information):**
 - OS: Debian stable
 - Wiki.js version: 2.0.12
 - Database engine: sqlite

**Comment by NGPixel** [comment]
Please [read the docs](https://docs.requarks.io/install/requirements#domain).

![image](https://user-images.githubusercontent.com/15522395/73565901-90ff7080-4430-11ea-9657-f588a52a1194.png)

**Comment by RossComputerGuy** [comment]
Why can't Wiki.js be mapped to a subfolder? Lots of projects like this have that functionality.

**Comment by RossComputerGuy** [comment]
I was trying to do this with the proxy stuff in Nginx.

**Comment by bs444** [comment]
> Please [read the docs](https://docs.requarks.io/install/requirements#domain).
> 
> ![image](https://user-images.githubusercontent.com/15522395/73565901-90ff7080-4430-11ea-9657-f588a52a1194.png)

@nicolas-giard:

1) "Unnecessary" is opinion. All features add complexity. That's the definition of a feature. Done right, it should actually simplify your code.

2) Path parsing not hard. Path permissions? Huh? You should just operate under some relative root path. It's not hard to take the path out of the forwarded header.

3) Path should not change except on installation, or serious maintenance. Rebuild is fine.

4) Cookie argument is invalid. Anyone running on subfolders will be running behind reverse proxy. All major reverse-proxies have reverse proxy settings for cookie paths and domain. You aren't expected to maintain cookies at both levels.

5) Path setting seems pretty clean to me. You shouldn't expend effort trying to 

Reasons: 

Subdomains are not allowed in many environments.
Strict security environments.
Internet isolated environment, or minimally, inbound being blocked = no let's encrypt.
Put aside the fact our environment will never relinquish control over subdomains, and their related certificates. 
Wildcard certificates are a security risk.
Greater control in containerized applications. I'm Not giving a docker container root http -serving authority.
This is something that has been solved countless times by countless other webapps. If you need help, I suggest you look at how other apps have solved it.

It sounds to me like your codebase is just too messy for yourself. If you don't know how to implement, just say that. Not that "subfolders are stupid."
 
Like many here, without subfolders, I will not be using Wiki.js.

**Comment by NGPixel** [comment]
@bs444 

1. This whole project is opinionated. Just because a subset of users want feature X, doesn't mean that it should be implemented. I build the project with the features I think are best and that means not all proposed features will be accepted.

2. When creating groups and page rules, is the user supposed to input the path without the sub-folder prefix? If not, I'm supposed to know that prefix already and remove it? What if the user didn't set that prefix previously? Considering a sub-folder prefix would be optional, it's not something I can warn the user about. None of his rules will work and the next thing you know, there're 10 new tickets opened on GitHub.

3. What about users writing all their links with the sub-folder path in them? Some company might decide to migrate their wiki to a new branding or rename the folder to a new team name. Then I would be expected to write a tool to rewrite all these links (and yes some users want that path to actually be part of the stored content, it's not something that can simply be discarded when saving).

4. The cookie argument is very much valid. This isn't about maintaining cookies at path X, it's about other apps running on the same domain messing up with the cookies or the localStorage set by wiki.js. Some apps will clear all cookies, regardless of the path, when logging out for example. Let's also not forget that ALL cookies set by other applications will have to be sent to the server on every single request. Let's say you have 15 applications on the same domain, each storing a login token in a cookie; this is somehow supposed to fit within the extremely small 4096 bytes limit? The JWT created by wiki.js already take a significant portion of that allowed size.

5. It might seem obvious to you, but from actual experience with this specific issue in v1, it's definitely not. It was a frequent problem and most of the support I had to deal with on GitHub issues or via chat was about incorrectly configured reverse-proxies.

Some of the reasons you mention are totally valid, that's not the issue here. But to me they are simply not worth all the downsides I listed. The codebase is not messy and it wouldn't be hard to implement at all. I simply don't think it's a good idea to implement it for the reasons I mentioned. I'd rather focus the very little time I have on actual development and not on customer support. To me, this is about managing the potential problems a user can have and the amount of tickets I would have to deal with.

Will that impact some users? Yes, and unfortunately in that situation, they'll have to look at other alternatives.

---

To further address some reasons you mentioned:

- Considering you would be using a reverse-proxy, I don't see how not having Let's Encrypt is an issue. Your reverse-proxy would already be handling SSL offloading. If not, Wiki.js can accept a custom certificate just fine.
- You're not forced to use wildcard certificates...? You can easily create a certificate for a specific sub-domain, which again can be handled by your reverse-proxy.
- Same thing with containerized applications, your reverse-proxy would handle sub-domain routing... You're not expected to expose the wiki directly to the internet or to let wiki.js handle SSL termination.

**Comment by ZacharyACoon** [comment]
> > Please [read the docs](https://docs.requarks.io/install/requirements#domain).
> > ![image](https://user-images.githubusercontent.com/15522395/73565901-90ff7080-4430-11ea-9657-f588a52a1194.png)
> 
> https://wiki.js.org/feedback/p/support-hosting-wikijs-at-subpath
> 
> @nicolas-giard:
> 
>     1. "Unnecessary" is opinion. All features add complexity. That's the definition of a feature. Done right, it should actually simplify your code.
> 
>     2. Path parsing not hard. Path permissions? Huh? You should just operate under some relative root path. It's not hard to take the path out of the forwarded header.
> 
>     3. Path should not change except on installation, or serious maintenance. Rebuild is fine.
> 
>     4. Cookie argument is invalid. Anyone running on subfolders will be running behind reverse proxy. All major reverse-proxies have reverse proxy settings for cookie paths and domain. You aren't expected to maintain cookies at both levels.
> 
>     5. Path setting seems pretty clean to me. You shouldn't expend effort trying to debug people's reverse-proxy setup.
> 
> 
> Reasons:
> 
> Subdomains are not allowed in many environments. Strict security environments. Internet isolated environment, or minimally, inbound being blocked = no let's encrypt. Put aside the fact our environment will never relinquish control over subdomains, and their related certificates. Wildcard certificates are a security risk. Greater control in containerized applications. I'm Not giving a docker container root http -serving authority. This is something that has been solved countless times by countless other webapps. If you need help, I suggest you look at how other apps have solved it.
> 
> It sounds to me like your codebase is just too messy for yourself. If you don't know how to implement, just say that. Not that "subfolders are stupid."
> 
> Like many here, without subfolders, I will not be using Wiki.js.

Application developers demanding that you run other subdomains for their applications is a huge problem.  The application should not dictate where it exists, and a subpath is a basic and easy thing to implement.

**Comment by RossComputerGuy** [comment]
> Application developers demanding that you run other subdomains for their applications is a huge problem. The application should not dictate where it exists, and a subpath is a basic and easy thing to implement.

MediaWiki works on subpaths

**Comment by NGPixel** [comment]
Then use MediaWiki. There's no plan to support it in Wiki.js. Move on.
