### ISSUE TITLE
Permissions seem to be validated in the frontend only

### ISSUE THREAD

**Issue by dakira** [Requarks/wiki#1424]
**Describe the bug**
A logged in user can still perform tasks that have been prohibited aster the user logged in.

**To Reproduce**
- Create page rules that allow the user to view and edit a site
- Login to the user account
- from another account disable writing for the user

**Expected behavior**
The user should not be able to edit the page but they can. Once logged out and back in, the correct permissions apply. This leads me to conclude that permissions are not checked server-side but somehow sent to the client on login, right?

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.0.12
 - Database engine: postgres 9.5.19

**Comment by NGPixel** [comment]
No, permissions are checked server-side. The issue is the JWT short expiration, which by default in 30 minutes. So if the user is already logged in, it can take up to 30 minutes before the token is renewed with the new permissions.

If that's an issue for you, you can put a shorter value in Admin > Authentication.

**Comment by dakira** [comment]
Okay, good to know. Thanks for taking the time to explain and building this amazing piece of software!
