### ISSUE TITLE
Files Whose Names Are Only Digits Cannot Be Renamed or Deleted

### ISSUE THREAD

**Issue by Marco77577** [Requarks/wiki#1492]
**Describe the bug**
Images (and probably files in general) cannot be renamed or deleted if their name consists of only a number (e.g., 1.png).

**To Reproduce**
1. Upload file named 1.png.
2. Try to rename or delete the file.

**Expected behavior**
I should be able to rename and delete the file.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/36480635/74734884-ce953380-524f-11ea-84e3-284920524380.PNG)
![Capture](https://user-images.githubusercontent.com/36480635/74734982-0c925780-5250-11ea-95e7-1fffcfa34f66.PNG)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.1.113
 - Database engine:  postgres 11.6

**Comment by sbonaime** [comment]
It is not a problem of digit in the name. You did not select the file you want to rename or delete ! 
In your screen shot, the 1.jpg file is not selected. if you selected it before clicking the action button, you can rename or delete it. 
Your problem is linked to #1493.
I think you can close this issue

**Comment by Marco77577** [comment]
You are right. Sorry, my fault!
