### ISSUE TITLE
Problems with the current version: 2.1.113

### ISSUE THREAD

**Issue by K69G4JRA725W** [Requarks/wiki#1499]
Problems with the current version: 2.1.113

1. The tag fields of each page should not be changed to lower cases! They should remain as entered.
2. In the page header search box, the search algorithm should be the same as that in the search after selection of tags.
3. The search should allow matching for multiple words separated by whitespace. If all search words are matched, the page is rated as 100%. If not a single word is matched, the page is rated 0%, and will not appear in the search results.
4. The list of tags for Chinese should be in Pin-Yin, and not by the first charater (or hieroglyph).
5. In the mobile device, the floating bubble in the lower left corner should be in the upper left corner where the icon is.

**Comment by NGPixel** [comment]
1. As designed. Prevents having duplicates of lowercase and uppercase versions.
2. Global search doesn't support tags yet. Coming in a future update.
3. This is already the case. Search behavior depends on the search engine used. For example, use Azure Search and it will work as you intend it.
4. Please create a feature request for this on https://wiki.js.org/feedback
5. This is a bug that will be fixed in 2.2.
