### ISSUE TITLE
Error in javascript console - wiki unusable

### ISSUE THREAD

**Issue by garbage-collector** [Requarks/wiki#151]
### Actual behavior
After installation, when I go to the wiki in my browser, the javascript does not seem to be loaded properly, and there is console log error : 

- In firefox : SyntaxError: missing = in const declaration app.min.js:1:733034
- In chrome : Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

It makes the wiki quite unusable.

FYI : I have exactly the same issue with https://docs.requarks.io/ : javascript console error and the website looks like something is missing.

I can give you a the URL of my installation if needed.

### Expected behavior
Working wiki

### Steps to reproduce the behavior
Just install a fresh wiki by following the official documentation

**Comment by NGPixel** [comment]
I just tested https://docs.requarks.io/ in the following browsers with **no errors**:

- Chrome 59
- Firefox 54
- Edge 41
- iOS 11 Beta Safari
- Safari Technology Preview

The current release of Safari has a bug that prevents the site from loading. This is fixed in their upcoming release. IE 11 has the same issue, which I'm still investigating.

Can you check if you have the latest version of Chrome and Firefox?
