### ISSUE TITLE
Maximum number of characters per page

### ISSUE THREAD

**Issue by mrmodolo** [Requarks/wiki#1584]
### Actual behavior
Version Wiki.js 2.1.113
When trying to compose a large document (94 Kb) in MarkDown it is no longer possible to save the page.
Alternatively we are breaking the pages into several smaller ones.
### Expected behavior
Be able to save the page in editing without size restriction or an alert of the maximum number of characters reached
### Steps to reproduce the behavior
Just try to save a page with lots of text (94 Kb or more)

**Comment by justinacolmena** [comment]
There is also the danger of running into process or memory limitations on JavaScript -- on either the node.js server or the user's browser.

Related (for large documents): the table of contents only lists ≤h1≥ and ≤h2≥ headings. Sub-subsections (and lower levels) h3-h6 are not listed in the t.o.c. -- possibly "to do" or "wish list" in my opinion -- but not that big of a deal because it is probably a better strategy or philosophy in general to break a large document into sub-pages and use the "subfolder" functionality with the "path" of 🍞 "breadcrumbs" at the top of the page to better organize the content.

On March 13, 2020 12:03:43 PM AKDT, "Marcelo Rezende Módolo" <notifications@github.com> wrote:
>>
>>
>### Actual behavior>
>Version Wiki.js 2.1.113>
>When trying to compose a large document (94 Kb) in MarkDown it is no
>longer possible to save the page.>
>Alternatively we are breaking the pages into several smaller ones.>
>### Expected behavior>
>Be able to save the page in editing without size restriction or an
>alert of the maximum number of characters reached>
>### Steps to reproduce the behavior>
>Just try to save a page with lots of text (94 Kb or more)>
>>
>>
>>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Requarks/wiki/issues/1584

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pdennis** [comment]
Just want to chime in that I'm also running into problems on big documents in the wysiwyg editor as well

**Comment by NGPixel** [comment]
This bug should be fixed in 2.2. I just tested saving a 780kb worth of markdown without any issue.
