### ISSUE TITLE
JSON API for adding entries?

### ISSUE THREAD

**Issue by ralphstodomingo** [Requarks/wiki#16]
Thank you for this project! 😄 
I just would like to ask if there's an API to add articles/entries.

**Comment by NGPixel** [comment]
There's no "official" API to add articles, but it's possible to do:

Send a **PUT** request to **/create/name-of-your-entry**
The request body must be a JSON object with the property `markdown` containing the markdown formatted content. E.g.:

```json
{
   "markdown": "YOUR CONTENT HERE"
}
```

The only issue for now is that you have to send a valid session token as a cookie with the request.

I'll mark this issue as an improvement request, as this is something that could easily be implemented (using an API token instead of session cookies).

**Comment by NGPixel** [comment]
Ticket moved to Feature Board: https://wikijs.canny.io/features/p/api-to-create--manage-pages

Closing this ticket.
