### ISSUE TITLE
Head HTMl Injection not applying in administration panel

### ISSUE THREAD

**Issue by rlarrode** [Requarks/wiki#1640]
**Describe the bug**
CSS sheet do not apply on administration panel whereas they are applied in the rest of the wiki

**To Reproduce**
1. Go to 'Administration'
2. Click on 'Themes'
3. In head HTML injection add a `<link href="/custom/css/file">`
4. Click on apply
5. Refresh
6. CSS link does no appears in console

**Expected behavior**
HTML HEAD Injection should also work in administration panel

**Host Info (please complete the following information):**
 - OS: Debian 9.10 on AWS EC2
 - Wiki.js version: 2.2.51
 - Database engine: postgres 9.5.20 on AWS RDS

**Additional context**
The only way i see is to update the master.pug file but i need to do it each time i upgrade wiki version

**Comment by sbonaime** [comment]
@rlarrode Something is missing for 3)

**Comment by rlarrode** [comment]
Thanks @sbonaime i've updated the issue

**Comment by sbonaime** [comment]
@rlarrode It is still missing something...
![Uploading Capture d’écran 2020-03-30 à 30-03-20 15.54.37.png…]()

**Comment by rlarrode** [comment]
it's better with quotes

**Comment by NGPixel** [comment]
This is by design. I'm not sure why you would want to style the administration area...

Considering it's a critical section of the wiki, it has to work the same for everybody in case you have a question or an issue. If an injected style or script cause the page to fail to render, you'd have to change it directly from the database.

If you absolutely want to style it, then you'll have to modify the source code directly.
