### ISSUE TITLE
Content page side menu doesn't scroll when there's overflow

### ISSUE THREAD

**Issue by samrawks** [Requarks/wiki#170]
### Actual behavior
More of an edge case here. I have a page where both the content overflows and so does the side menu because of how many anchors there are in the page. It's a logins page so there needs to be a lot of anchors in the side menu.

The problem is that I can't scroll down in the page's side menu because it's disabled until the page content has been fully scrolled.

### Expected behavior
I expected the side menu to be scrollable (at least on hover) regardless of how far down the main content I am.

### Steps to reproduce the behavior
1. Create a page where the main content and the side menu content are longer than the viewport.
2. Try to scroll the side menu.

Made a demo gif: https://gfycat.com/gifs/detail/BiodegradableThriftyBellsnake

**Comment by dougrday** [comment]
Note that the smooth scrolling jQuery plugin isn't compatible with this fix, so I've removed it.

**Comment by xiaojie45** [comment]
i encounter the same problem,  there are many anchors in the sidebar, but the anchors could not scroll with the content in the left. because the content is so much, it is painful for our team members to scroll down to find the right content. add some css to the 'sidebar-pagecontents' class can make the sidebar scroll just like this
![image](https://user-images.githubusercontent.com/17947860/35315023-1648021e-0105-11e8-8ed1-ba3d341b643e.png)

**Comment by cmpickle** [comment]
@NGPixel Is someone still working on this or is this one that I could start working on?

**Comment by NGPixel** [comment]
Fixed in 2.0.
