### ISSUE TITLE
Error when deleting asset containing "-".

### ISSUE THREAD

**Issue by mattlundstrom** [Requarks/wiki#1770]
**Describe the bug**
Attempting to delete an asset that contains a dash ("-") using the HTML WYSIWG asset manager results in "Variable "$id" of non-null type "Int!" must not be null."

**To Reproduce**
1. Go to 'any page's edit screen'
2. Click on 'asset manager'
3. Click '...' next to any file that contains a "-" that you wish to delete.
4. Click "Delete"
5. See error

**Expected behavior**
The file should delete. 

**Host Info (please complete the following information):**
 - OS: OSX 10.15.3 
 - Wiki.js version: 2.2.51
 - Database engine: postgres 11.7

**Additional context**
As a temp workaround can I delete assets through the filesystem without incident?

**Comment by NGPixel** [comment]
This has nothing to do with the filename containing a dash. You need to select the row you want to delete and then click the [...] button and select Delete. This error occurs when you don't select the row first.

This is fixed in 2.3.

Also deleting the asset from the filesystem doesn't actually deletes it as it is stored in the DB.
