### ISSUE TITLE
Unable to Override CSS via Code Injection

### ISSUE THREAD

**Issue by dfuentes03** [Requarks/wiki#1809]
Added the following to CSS Override in Admin to change the font color of the 'Table of Contents' text:
```
.v-application .primary--text {
    color: #B8353B !important;
    caret-color: #B8353B !important;
}
```

The default blue font, however, isn't overridden:
![Screen Shot 2020-04-30 at 5 18 03 PM](https://user-images.githubusercontent.com/48250453/80760856-95a6f400-8b07-11ea-9e22-dc0d4ed43fcc.png)

Is there anything I'm missing?

**Comment by Smankusors** [comment]
well then, you need more specific CSS rule. Like `.v-application .v-content .primary--text`

**Comment by NGPixel** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by JussiKivimaki** [comment]
Admin panel says below the css injection box that it's applied **after** the default styles. (_"CSS code to inject after system default CSS."_) However, in the rendered page the override style block is **before** the default styles. At least on my Windows install. 

Either change the order how the override styles are loaded or change the description text? I'd prefer the former, since then overriding the default styles would be easier.

**Comment by Metismos** [comment]
This is the case for me also.
