### ISSUE TITLE
Icons not working after upgrading to 2.3.81

### ISSUE THREAD

**Issue by NiCkBuRRiTo** [Requarks/wiki#1817]
Most of the icons all over the wiki appear as an empty box after upgrading to the latest version.

![Annotation 2020-05-01 195531](https://user-images.githubusercontent.com/49071478/80847372-c4939780-8be5-11ea-853e-b7be9922f033.jpg)

**Comment by rlarrode** [comment]
Hello,
Do you clean your browser cache?
Do you restart your server after update?
Does your wiki accessible using CloudFlare (need to clean CloudFlare cache)?

**Comment by asalam05** [comment]
Hello @NiCkBuRRiTo ,

It may be because of the Locales loading issue. I too had the same problem after upgrading to latest version 2.3.81. It didn't give me any error even after updating the lastest version, but the locales file was missing while i checked in the administration page. Please refer this [document](https://docs.requarks.io/en/install/sideload), it may help you.

**Comment by NGPixel** [comment]
This is not a locales issue. You simply need to clear your cache (browser AND reverse-proxy (if any)).
