### ISSUE TITLE
Document exceeds maximum size allowed by Algolia

### ISSUE THREAD

**Issue by wlfcss** [Requarks/wiki#1833]
**Describe the bug**
an error toast：Document exceeds maximum size allowed by Algolia.

**To Reproduce**
1. chose the search Engine：Algolia
2. Fill in the APPID & Admin API Key  correctly
3. **Rebuild Index** then Save these settings
4. See error：Document exceeds maximum size allowed by Algolia

**Expected behavior**
I hope Algolia works，but is not, I read the docs about the Algolia,But this error seems to have nothing to do with my Alogia subscription plan，Maybe I got it wrong？

**Host Info (please complete the following information):**
 - local：OSX 10.15.3 - Chrome 81.0.4044.122
 - server-OS: [ubuntu18.04]
 - Wiki.js version: [latest 2.3.77]
 - Database engine: [postgres]
 - language: ZH-cn

**Additional context**
 - none

**Comment by fferraro87** [comment]
same problem here

**Comment by bmann** [comment]
Just set this up, getting it as well

**Comment by wlfcss** [comment]
> Just set this up, getting it as well

![image](https://user-images.githubusercontent.com/12138285/83115793-7cd93080-a0fd-11ea-9b79-bcf843886f73.png)

- doesn’t seem to be working

**Comment by JorgenSolli** [comment]
Having the same issue.

**Comment by jayzalowitz** [comment]
Same issue here.

**Comment by jayzalowitz** [comment]
https://github.com/Requarks/wiki/issues/2089

**Comment by jayzalowitz** [comment]
Describe the bug
When you have a large document this gets thrown and no documents get indexed:
https://github.com/Requarks/wiki/blob/master/server/modules/search/algolia/engine.js#L142

To Reproduce
Make a very large document

Expected behavior
At least some documents would get through

Additional context
https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/ splitting by line would work just as well for these documents. At the very least telling what document was causing the problem would be great while trying to rebuild index.

**Comment by jayzalowitz** [comment]
Skipping indexing of those docs instead of failing for all indexes would be a great temp fix.

**Comment by MisterRee** [comment]
Same issue. Would be great to get a fix for this, a wiki without the ability to efficiently search the data is useless.

**Comment by tobias-graf-p** [comment]
Same issue here. Would be great if this could be fixed soon.

**Comment by joppehoekstra** [comment]
Same issue here. A solution would be very much appreciated!

**Comment by lcalem** [comment]
I'm having the same issue and would probably agree with temporarily removing or splitting the large document while an "ignore larger files" option is implemented but I don't even know which document is too big. Maybe as a quick improvement including the name of the problematic document in the message would be helpful?
