### ISSUE TITLE
Save-and-close with background rendering

### ISSUE THREAD

**Issue by madduck** [Requarks/wiki#1845]
This is a feature request, because `canny.io` seems broken, and I don't want to lose what I wrote. Maybe someone can import it when things are fixed again? I'll also try in a few days again.

![image](https://user-images.githubusercontent.com/195073/81235851-08582800-9050-11ea-826f-91f2057b5d94.png)

Especially with sites that are further away (i.e. high latency), saving a page means waiting a few seconds while rendering, only to then be able to close the page.

I wish there was a way to save-close the page with rendering in the background, and a push of the updated content once rendered.

That said, why does rendering take more than a fraction of a second anyway?

**Comment by NGPixel** [comment]
Try via https://requarks.canny.io/wiki

It takes some time to render because it actually starts a separate process to do so. This ensures complex rendering doesn't affect the main process and that if a crash occurs, only that page is affected. Also keep in mind that there are many other operations taking place at the same time:
- save on storage targets (git, etc.)
- update search index
- reconnect links
- rebuild page tree
- write to cache
etc.
