### ISSUE TITLE
Cannot operate behind HTTP basic auth proxy

### ISSUE THREAD

**Issue by madduck** [Requarks/wiki#1846]
WikiJS cannot run behind a Basic Auth HTTP server. If I attempt that, I get lots of errors, and site labels don't get rendered properly:

![Screenshot_2020-05-05 Admin(1)](https://user-images.githubusercontent.com/195073/81240596-e95f9300-905b-11ea-9405-81da8e6fe0a1.png)

Turning off basic auth resolves this. This was also confirmed by another user on Slack.

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.3.81
 - Database engine: PostgreSQL 11.7

**Comment by NGPixel** [comment]
HTTP Basic Auth is not supported and there's no plan to support it. Wiki.js already has authentication capabilities built-in.

**Comment by winkelement** [comment]
I don't want to argue about that but maybe i can explain why i also tried to run HTTP basic auth for the wiki (i'm the Slack user mentioned above).

I am going to use the wiki as an internal only wiki for a small NGO. It might contain sensitive data. I need to expose the wiki to the internet. Users are synced to LDAP. LDAP passwords are very weak (don't ask why). 2FA is not available yet. So i just wanted to have HTTP basic auth as a first security barrier. It also makes it easy to run a fail2ban filter against it and block recuring failed logins attempts before they hit the actual wiki.

Anyway i just wanted to explain why trying to use HTTP basic auth is not necessarily a sign of being to lazy to set up a authentication method 😄

**Comment by ws-h-ono** [comment]
Agree to have basic auth support.

I don't want to expose the URL to show that it is a wiki, which could also expose vulnerabilities if any exists at one point.

Basic auth hides what's behind the URL and it would be better if basic auth information can be used as a user name for the wiki logged in without its built-in login mechanism. (Having the user created automatically on first login would be handy.)

**Comment by ws-h-ono** [comment]
Currently, if I disable basic auth for `/graphql`, it works with other parts covered with basic auth.

**Comment by btittelbach** [comment]
This is still an open problem. If have the exact same requirements as winkelement and I am uncomfortable opening up graphql to outside attacks. Wikijs as a whole seems to still be heavily in development (e.g. the only half-working oauth2 support which e.g does not work with common applications like nextcloud) and is thus likely not security hardened.

I spent weeks preparing the introduction of wikijs and now I may have to scrap it all because wikijs is overwriting the HTTP basic auth header when using graphql

**Comment by NGPixel** [comment]
@btittelbach You realize that http basic auth is insecure right? It offers really poor protection which is why there's no plan to support it. If your concept of security is to hide everything behind a weak protocol like http auth, you're completely missing the point.

The oauth2 module is not "half-working". It supports only one of the many flows for now. More will be added in the future. Just because it doesn't support yours at the moment doesn't make it "not Security hardened" like you pretend. Please don't make completely baseless claims.

**Comment by madduck** [comment]
@NGPixel Please read the thread instead of just waving your teacher wand about HTTP Basic Auth. There are very legitimate use-cases. In fact, HTTP Basic Auth makes a very good 2FA layer in certain ways, and for certain use-cases.

**Comment by nasiralamreeki** [comment]
> @NGPixel Please read the thread instead of just waving your teacher wand about HTTP Basic Auth. There are very legitimate use-cases. In fact, HTTP Basic Auth makes a very good 2FA layer in certain ways, and for certain use-cases.

He's literally not waving his teacher wand. HTTP Basic Auth isn't secure and he is the project leader and developer so he decides what is in the roadmap and what isn't on the roadmap.

**Comment by NGPixel** [comment]
@madduck This isn't about whether I like it or not. Wiki.js is using Bearer tokens in the Authorization header. You can't have multiple authorization headers at the same time, it's simply not possible. It's either Basic or Bearer Token. I'm not gonna start adding sketchy workarounds with unsupported alternate headers simply to support a poor security practice.

Is HTTP Basic a quick and simple way to add an additional security layer? Yes. But it still remains a weak protocol and it conflicts with the bearer token authorization header used by Wiki.js. So either rethink your security strategy or don't use Wiki.js, it's as simple as that.

**Comment by madduck** [comment]
Thank you, @NGPixel, that makes sense.

**Comment by btittelbach** [comment]
first of all: Thanks for reading closed issues ;-)
second: I certainly did not want to come of as overly criticizing. I compared a lot of self-hosted wikis over the last months and choose wikijs for a reason. You definitely did some very good work here. I just wish you could do more faster ;-D But really that's a problem we all share in every project.

You are correct that http basic auth isn't secure and digest auth via ssl (which is what i'm actually using) isn't perfect ether. It is however a nice second layer of security, whose level of security I can quickly judge, whereas, no matter how perfect wikijs's security may be, is much more complex and harder to review. Deploying the first, can buy time for the later.

I agree that if workarounds are necessary, in order to support http*auth, it's better not to implement this at all.
Thank you for that clarification, that alleviates quite a bit of frustration! :-)
