### ISSUE TITLE
Alternate Authentication

### ISSUE THREAD

**Issue by oshybrid** [Requarks/wiki#1943]
I am working on the Network Operation Wiki page for the company I am at.  I wanted to make the "Company-Wide" page open and not require any login (the public-facing page).  But I wanted to make those in operations login to the page to get the "NOC only" view that contains information that we would not want other groups privy to (local login to network devices we manage).

Obviously Wiki.js can do this.  But is there a way or works around that allows Wiki.js to bounce those login request to be forwarded and authenticated by Operation's TACACS server?  It is the philosophy of the company (as well as my own), that local logins are not to be set and used unless absolutely necessary (root access, restoring an offline node, etc).

**Comment by NGPixel** [comment]
I haven't found any passport.js module for TACACS _(first time I'm hearing about this protocol, I had to look it up)_. So unless you're willing to write one, it won't be possible.

You can always post a request for TACACS authentication on https://requests.requarks.io/wiki
but like I said, there's no module for it and I'm not the one who would be writing it.

I would suggest looking into other more common enterprise auth solutions (LDAP, SAML, etc.) which are already supported. Otherwise local authentication would be your only option.
