### ISSUE TITLE
An option to remove "Source" from navbar

### ISSUE THREAD

**Issue by Bamieh** [Requarks/wiki#221]
I find the "Source" button in the navbar a bit annoying, and i dont want it to be there for my users. I see no way to hiding it. I suggest that we add something like a config option to hide it? or just show it to those who can edit the pages?

something like:
```yml
viewSource: "admin" | "all" | "none"
```

**Comment by Bamieh** [comment]
if you agree upon it i can implement it right away.

P.S. I was using something like python notebooks, and they have a great feature of the ability to extend the template or override it by having a src file in the root file of the running wiki. what do you think about that?

**Comment by NGPixel** [comment]
Having the source button as an option is a good idea.

I'm not sure I understand your template override feature?

**Comment by Bamieh** [comment]
@NGPixel i'll open a separate issue for it so we can discuss it.

**Comment by XerqJon** [comment]
My apologies if this is a stupid question but I am having a problem, but how exactly do I use this option? As I do not see an option in the settings UI, I have edited the config.yml to read
`theme:
  primary: cyan
  alt: blue-grey
  viewSource: false`

and I get a 503 error when I restart wiki. I have also tried _none_ instead of _false_ but that returned the same error. The only value I can put there seems to be 503. Short of going in and removing the "Source" button from the templates I am not sure what to do.
