### ISSUE TITLE
Anchor links doesn't move to the correct header/title

### ISSUE THREAD

**Issue by Dezent** [Requarks/wiki#233]
### Actual behavior
Using an anchor link doesn't move the page to the correct header if the link is pressed from another article. 
### Expected behavior

When anchor link is pressed, new article is opened at the correct header/title.

### Steps to reproduce the behavior

Press anchor link from another page.

**Comment by NGPixel** [comment]
I can't reproduce your issue.

See this page as example:
https://docs.requarks.io/wiki/install#more

The `here` text links to specific section on another page, which works fine.

**Comment by XerqJon** [comment]
I'm experiencing this as well. I initially thought it was related to a websocket error (mentioned in Gitter but you told me it was not).

I created a table of contents on the home page linking to all of the sub-pages (about 8) with multiple headers on each. For instance if I click on the link on the home page pointing to _site.com/help/anchor#6-3-3-header_ instead of scrolling down to section 6-3-3 (6th page, 3rd section, 3rd sub section) I am _either_ taken to the top of the page _or_ sometimes I'll end up somewhere near 6-2-2.  

@Dezent I don't know about you but my pages have images on them and I read somewhere that images (maybe just ones without any size attributes) could cause a problem because the browser attempts to scroll to the target before the images load and extend the length of the page.

I am working with my team to test this theory (going to duplicate some pages and remove all images) and I will report back.

@NGPixel - I don't know if this is something that you could compensate for if the images do turn out to be the problem.  I'm happy to share the URL to my instance via a PM if you would like to see what we are referring to in action.

**Comment by NGPixel** [comment]
@XerqJon Can you try to link to an header that doesn't start with numbers? For example, "sample header". Does that work?

**Comment by XerqJon** [comment]
@NGPixel that _may_ have something to do with it. What I am noticing is a lot of the header links originally generated (with numbers) kept the same CASE as the headers themselves, but as I look through the sidebar navigation I see they have all been converted to lower-case urls - this may be part of the reason they aren't working. I've fixed a few of the old ones and it didn't change.

We're going to do some more thorough testing without the numbers and let you know. We would prefer to keep them in there but if it will prevent the site from functioning properly we'll remove them.

**Comment by NGPixel** [comment]
@XerqJon This is just to pinpoint the root cause. If numbers are the issue, then it's easier to apply a fix.

**Comment by XerqJon** [comment]
I don't think it's the numbers after all. My colleague may have used incorrect case with the URLs that I previously mentioned.

The scrolling issue persists with or without numbers. It does appear to be related to images. After removing several images from my page I am getting to the proper header from my table of contents. My next step is to have my colleague add size attributes to each image on a page to see if that helps.

**Comment by XerqJon** [comment]
@Dezent & @NGPixel We have confirmed on our end that the issue is/was not having a defined size for our images. Adding `{ width=X ; height=X}` to the end of the image tag worked like a charm. We are now going through and updating each of our entries with a size attribute. @Dezent I don't know if you have images as well or if you are experiencing something else.

With that said, I guess this isn't much of a Wiki.JS issue but rather how browsers load/render websites. It would be awfully cool if something could be done to compensate for images. That's over my head though. Thanks.
