### ISSUE TITLE
2.5.159 version wiki.js Microsoft Edge Browser only display Show blank page

### ISSUE THREAD

**Issue by ilanni2460** [Requarks/wiki#2565]
2.5.159 version wiki.js Microsoft Edge Browser only display Show blank page

**Comment by NGPixel** [comment]
https://docs.requarks.io/ is running 2.5.159 and it works just fine in Edge.

**Comment by jtapsl** [comment]
I see the same issue. I'm running the legacy Microsoft Edge (not the new Chrome-based one).
Microsoft Edge 44.19041.423.0
Microsoft EdgeHTML 18.19041

The console shows this error:
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
app.js (19,3171)
Which seems to refer to line 19, character 3171

**Comment by jtapsl** [comment]
Same issue on https://docs.requarks.io/ except that instead of a blank page it shows "You are using an outdated browser" followed by a broken link to https://www.whatbrowser.org/intl/en-US/ . On https://docs.requarks.io/ I get the same "Expected identifier, string or number" error as on a locally-hosted instance.

**Comment by NGPixel** [comment]
The legacy MS Edge is not supported. Please upgrade to the latest one (chromium-based).
