### ISSUE TITLE
How do I install WikiJS 3 dev?

### ISSUE THREAD

**Issue by Emaxoso** [Requarks/wiki#2622]
Hi, I'm running WikiJS on the latest docker version, is WikiJS 3 dev available as an image?
I couldn't find it on docker hub

**Comment by Smankusors** [comment]
how about canary? 🤔

**Comment by ponsfrilus** [comment]
Both canary and beta image shows version 2.5.170.

**Comment by NGPixel** [comment]
3.0 is nowhere ready to be tested. Instructions will be provided further into development.

**Comment by kylebakerio** [comment]
I tried looking around, and have loosely been following for several months. I was holding back launching a wiki because there are some dealbreaker issues that are on the roadmap for 3.

Is there a beta of 3 that is available to test? Is 3 expected to release soon, or is it just stuck in purgatory and could be another 6mo -> 1yr+, or is it on hold, or is there a clear place to follow its status, or...?

**Comment by NGPixel** [comment]
No beta to test at the moment. You can follow the progress on blog.js.wiki.

3.0 is still under active development.

**Comment by saneklad** [comment]
> 3.0 is still under active development.

Are there any news from June about planned dates for the start of beta testing?
