### ISSUE TITLE
Rename a directory

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2631]
**Question**
Hello,
What is the procedure to rename a directory ? For instance I have a directory called database and I would like it to become Databases.
Thanks

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 2.5.159
Database engine:postgres 9.6.17

**Comment by Igorgro** [comment]
There are two ways available. The first way is to change of all page inside this folder because all folders are virtual and generate by analysing page paths. Another way is to create a "main" page in the folder by creating it with the same path as that folder. As example if you want to rename folder /database you can create a page named "Databases" with path "/database". This page will become a "main" page in that folder and the folder name in left menu will change to "Databases". Keep in mind that this will only create alias for directory and not rename it, because all pages inside that directory will still have path lik "/database/somepage".

**Comment by ankyfive** [comment]
Ok thanks for your help
