### ISSUE TITLE
Ability to mark jwt Cookie as httpOnly and secure

### ISSUE THREAD

**Issue by madflow** [Requarks/wiki#2708]
**Describe the bug**

First of all: Very nice Wiki project. And apologies - this is a mixture of a Bug Report and Feature request.

**Expected behavior**

As far as I can see (and I could be mistaken) it is not possible to mark the authentication cookie as `httpOnly` (because it it read via [Javascript](https://github.com/Requarks/wiki/blob/74ee7823adbabb4205d126ab851b5ac9a9ad6f2f/client/client-app.js#L96) )

and also - I do not see a way to mark the cookie as `secure`.

Both measures are usually "good practice". 

I have not grasped all of the implementation details yet - but I would assume, that it is not necessary to read the cookie and set a extra auth header - since cookies (when `fetch` is configure correctly) are being send on every request.

So the feature request is: set the authentication cookie as `httpOnly` and set it to `secure` in production.

**Comment by NGPixel** [comment]
1) The JWT must be readable from javascript, not just the server so httpOnly is not an option.
2) The cookie is marked as secure when HTTPS is enabled in Wiki.js. Although this won't be the case if using a reverse-proxy instead.
3) The JWT is sent via the auth headers because the API accepts external calls as well, which can't use cookies.

The cookie is being deprecated completely in the upcoming 3.0 update.
