### ISSUE TITLE
EACCES: permission denied, mkdir '/ home / wiki'

### ISSUE THREAD

**Issue by eduardoleallima** [Requarks/wiki#2827]
Everything we are going to do on our wiki has a permission error.

**EACCES: permission denied, mkdir '/ home / wiki'**
![wiki](https://user-images.githubusercontent.com/26935908/102268643-555f7f00-3efa-11eb-9269-0ab9bc2eac55.png)

Do you know how to solve it?

Thank you very much in advance

**Comment by eduardoleallima** [comment]
We are using Ubuntu 18.04 LTS
We followed the Wiki.js standard installation tutorial

Docker
PostgreSQL 11 (dockerized)
Wiki.js 2.x (dockerized, accessible via port 80)
Wiki.js Update Companion (dockerized)
OpenSSH with UFW Firewall preconfigured for SSH, HTTP and HTTPS

**Comment by NGPixel** [comment]
Make sure the node process has write permission to the path you specified.

**Comment by ansonphong** [comment]
I am having the same issue, and Node definitely does have write permission since the write operation is occurring, though it still throws this error, which is confusing for anybody trying to edit the wiki.

`EACCES: permission denied, mkdir '/var/wiki_vs_import'`

We have made two extensive attempts to fix this and set permissions so far with no avail, any more specifics or clues to solve this would be helpful, thanks.
