### ISSUE TITLE
Incorrect pages id when searching on PostgreSQL (GraphQL)

### ISSUE THREAD

**Issue by alexfromvl** [requarks/wiki#2938]
**Describe the bug**
When switching the search engine from the standard "Database - Basic" to "Database - PostgreSQL", pages id change when searching using GraphQL - query pages search.

**To Reproduce**
1. Go to the admin panel, go to the Search Engine 
2. Сhange search engine settings from the standard "Database - Basic" to "Database - PostgreSQL", refresh the index
3. Check page id in admin panel
4. Request page search using GraphQL - query pages search:
```
query {
  pages {
    search(path: "page/page1", locale: "en", query: "") {
      results {
        id
        title
        description
        path
        locale
      }
    }
  }
}
```
4. Retrieve a different id which does not match the page id
5. Go back to admin panel, set search engine to default "Database - Basic"
6. Repeat the page search query using GraphQL
7. Get the correct page id

**Expected behavior**
When searching with "Database - PostgreSQL" get the same page id as specified in the page properties.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.5.170
 - Database engine: postgres 11.10

**Comment by NGPixel** [comment]
The id field is not the page ID but the search result ID (or more specifically the pagesVector table ID). It is meant to be a unique identifier to loop through results.

The reason you get the correct ID when using Database Basic is that it's searching directly in the pages table. Other search engines can use any other unique identifier; most use the page hash or self-generated IDs.

It could be a good idea to add the page ID as a queryable fields in search results though.

**Comment by splumhoff** [comment]
Hi @NGPixel ,

ran into the same issue.
My expectation was, that the returned ID can be used to retrieve content pages via 
```
query {
  pages {
    single(id: IDFromSearchResults) {
      id
      title
      description
      content
    }
  }
}

```
It seems that the search result ID can't be used to retrieve the content, so there might be no way to retrieve the page content via GraphQL when using the non-standard search engine. The search result id would not usefull at all in that case.
Maybe I'm mising something.

**Comment by Aeyd** [comment]
Hi @NGPixel,

we ran into the same issue. Searching on the database works just fine. As soon as we switched to Database - PostgreSQL search, wrong page id's are returned. 

We use the search query to find out if a page is already existing at a specified path. If the page is already existing we need the page id to make an update query. Otherwise, a new page is created on this path.

```
query Page($path: String!) {
  pages {
    search(query: $path, path: $path, locale: "en") {
      results {
        id
      }
    }
  }
}
```

We need this feature otherwise, we can't use wiki.js. We can't use the standard database search, because this search doesn't search page content. This content-based search is the main reason why we have chosen wiki.js in the first place.

As a workaround - Is there any other way to check if a page is already existing? How to get the page id if you know the path?

**Comment by dhurley94** [comment]
We have a similar problem and don't have access to the page tags. Another workaround is where you can take the path result from PageQuery.list() and pass it to PageQuery.tree() to get the page's id.

```
query ($path: String!, $locale: String!) {
  pages {
    tree(path: $path, locale: $locale, mode: ALL) {
      id
    }
  }
}
```

**Comment by NGPixel** [comment]
Addressed in v3.
