### ISSUE TITLE
Creating Folders and Uploading/Fetching Images Through the Built-In Modal Does Not Work.

### ISSUE THREAD

**Issue by thomasmiguelthompson** [Requarks/wiki#30]
![image](https://cloud.githubusercontent.com/assets/23084833/23830997/cecb0272-06d4-11e7-809d-c26593f786c4.png)

As you can see here, uploading an image gets stuck on "Uploading... 100%"
Not sure if we have an issue with CHOWN or what ¯\_(ツ)_/¯
Many thanks! (may be related to #10, but I wasn't sure exactly what happened there, the convo flip-flopped)

**Comment by NGPixel** [comment]
Are you using a web server in front of Wiki.js? e.g. nginx / apache

This usually happens because you uploaded a file larger than the web server upload limits. Right now there's a bug where it just get stuck in this stuck. This has been fixed in the upcoming release where an error message is displayed.

**Comment by nullpixel1** [comment]
Yeah, using nginx to reverse proxy. I'll check the upload limit now

**Comment by oivindoh** [comment]
Somewhat possibly related; could access rights on repo/uploads be related to this? When I start wiki the access rights keep reverting to this state where the user I run the app with is unable to browse the directory.

**Comment by steckerhalter** [comment]
Same for me too. On `/repo/uploads` the `x` flag is getting removed hence node cannot access the files under `uploads`.

**Comment by nullpixel1** [comment]
```0|wiki     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|wiki     | Error: EACCES: permission denied, mkdir '/home/wiki/wiki/repo/uploads/wiki'
0|wiki     | Unhandled rejection Error: EACCES: permission denied, mkdir '/home/wiki/wiki/repo/uploads/wiki'
0|wiki     | Unhandled rejection Error: EACCES: permission denied, mkdir '/home/wiki/wiki/repo/uploads/tesy'```

**Comment by DawidCh** [comment]
Hi.
I have just configured to start wiki.js as root, so access rights should not be a problem. I'm getting error in the logs that sharp module cannot be found. I can't install it using npm because gyp fails.
Do you have any ideas? The error is being thrown during listing folder in the upload dialog.

**Comment by steckerhalter** [comment]
Yeah, I have this error too but I thought it probably doesn't matter. Maybe this **is** a problem then?

**Comment by NGPixel** [comment]
The `Cannot find module 'sharp'` error occurs because you did not install the Node.js compilation dependencies as required:

https://docs.wiki.requarks.io/prerequisites#node-js-native-compilation-support

Then run `npm install && npm rebuild`

Uploads will fail if the sharp module can't be loaded.

Beta 9 will completely remove any native compilation dependencies so these errors will be a thing of the past.

**Comment by steckerhalter** [comment]
@NGPixel I installed `node-gyp` now. The `sharp` module error is gone but it still doesn't work (timeout on upload at 100%). The `x` permissions on the `uploads` folder is getting removed when starting the wiki hence the directory contents are unreadable by node or git.

**Comment by NGPixel** [comment]
The permission bug has been fixed for Beta 9.

**Comment by steckerhalter** [comment]
@NGPixel thanks. do you have these changes in another repository? I would like to be able to use the fixes already if possible :)

**Comment by NGPixel** [comment]
Simply replace the following file `/libs/local.js`:

https://github.com/Requarks/wiki/blob/master/libs/local.js

**Comment by steckerhalter** [comment]
@NGPixel I'm using the latest master now, thanks. The permission issue is solved. The uploads work too but the contents of the folders are always shown empty. Are the contents saved in the db btw? Because when I delete them in the repo they are still visible in the UI.

**Comment by NGPixel** [comment]
Files and documents contents are not saved in the DB. However, a list of files and their basic metadata is saved in the DB as cache (which is what you see in the Insert Images / Files modals).

If you restart Wiki.js, that cache will be erased and a new list of files will be created based on a folder scan.

The images modal will only show image files (.jpg, .png, .gif), even if you upload other file types.

**Comment by eriknelson** [comment]
Can confirm the new `local.js` fixed this issue for me as well. I bounced the server with a `node wiki stop && node wiki start` and it accepted a file upload right away and displayed it correctly.

Thanks!
