### ISSUE TITLE
Development halted?

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#3013]
Seems like not much is happening except Backers updates?

**Comment by nuraeil** [comment]
> Seems like not much is happening except Backers updates?

I would stronlgy disagree that the development is halted. He is actively working on version 3 of Wiki.js (https://github.com/Requarks/wiki-vnext) and recently also merged a couple of pull requests.

Version 3 is still in-progress and it even says on the Release Notes page, that it is expected Q1/Q2 of 2021. 

_This build is under active development and has not yet been released.
ETA: Q1/Q2 2021_

Source: https://docs.requarks.io/releases, Date 03.02.2021 15:04 GMT+1 (Berlin)

I believe that his main focus lies on getting version 3 ready, which is a humongous task for one person.

He is still only one person doing all the heavy-work, so please cut him some slack and be patient. I am also looking forward to the next version as my company wants to implement his software but I still am patient as I know how much work the new version is. It will add a lot of things. 

Just checkout the current state of the next version and the roadmap. I believe you will come to the same conclusion as I have.

Also, feel free to read his FAQ about new releases: https://docs.requarks.io/releases/about

I hope I did not sound too harsh and if I did, I would like to apologize beforehand for it.

**Comment by AuspeXeu** [comment]
Thanks for taking the time to comment on this @nuraeil I didn't mean to be rude. Just wanted to poke and see if things are still moving.

**Comment by nuraeil** [comment]
> Thanks for taking the time to comment on this @nuraeil I didn't mean to be rude. Just wanted to poke and see if things are still moving.
> 
> Edit: I am just surprised that he's working on version 3 now even though I had the impression version 2 was not complete by any means. Or did I get that wrong?

All good, it did not seem rude :) I just thought I could chime-in and give some insight as far as to what I had observed.

And I believe some features are planned for after version 3 rather than 2. V3 reworks a lot of things and might even allow some features to be implemented in an easier way or even at all. But these are just my guesses. 

Most features are still planned or even in-progress that were requested. Take a look here: https://docs.requarks.io/releases/roadmap. Lots of features are on the roadmap for 3.X

Also, he features the progress on his blog: https://blog.js.wiki/news?tag=3.x

**Comment by NGPixel** [comment]
Pretty much what @nuraeil said ^^ 😄
