### ISSUE TITLE
Public "create account" option?

### ISSUE THREAD

**Issue by eriknelson** [Requarks/wiki#41]
Is there a way to enable a public "create account" so that people and register themselves with the wiki and gain access? It looks like right now, it's the admin's responsibility to add users.

**Comment by NGPixel** [comment]
I can add the option if you need it. The reason I didn't add it at first is because anyone could create an account and write spam or delete content.

**Comment by eriknelson** [comment]
Makes sense. I can work around it since we don't have too many people, but I think this would serve people who are running it on a LAN or intranet for their team. It's not publicly exposed and allows team members to just sign up themselves.

Just a switch I was hoping to find. Thanks again!

**Comment by NGPixel** [comment]
Makes sense for a LAN scenario. Will add the option in Beta 10.

**Comment by peragwin** [comment]
Along the same vein, would it be possible to include a setting that would allow auth providers to create accounts automatically? (Similarly, to be used in a LAN scenario such as in my case where all the users already have Google accounts)

**Comment by NGPixel** [comment]
Moved ticket to Feature Board: https://wikijs.canny.io/features/p/public-account-registration

Closing this ticket.

**Comment by easly1989** [comment]
Hello, i know this is an old issue, but i didn't  want to open a new one.

I'm using your wiki for a local wiki, and i need people to be able to register themselves

Would you please tell me what to do to enable the local registration?
Does this "switch" you were talking about exists?

Thank you in advance,

**Comment by NGPixel** [comment]
This is coming in 2.0.

**Comment by felipevsw** [comment]
Can this be local only? From my testing here when the user is created an email is sent with some confirmation link, which on my case it's not applicable because I do not have a mail server set up (and will never have one). 
The user is created, but when the user tries to login an error message says they need to confirm their account, which is impossible since the wiki is not connected to a mail server.

Can this be account verification step be disabled? So the user could log in after the account is created.
