### ISSUE TITLE
Why a separate installation script

### ISSUE THREAD

**Issue by emranbm** [Requarks/wiki#463]
Hello,
Thanks a lot for the platform. It's nice and handy.
But, as a node.js developer, I don't understand why did you make the installation process so complicated?
### Actual behavior
When installing wiki.js by npm, wiki.js downloads that another script (https://wiki.js.org/install.sh or https://wiki.js.org/install.ps1 based on the OS) and the script itself downloads and configures the project files and its dependencies (node_modules) as **tar.gz files**, from the project's github release page.  
Isn't it better to let the npm do the job itself? Since it is itself a **dependency manger** designed for such tasks!
### Expected behavior
I think a better way is to guide developers do this:
```bash
$ git pull https://github.com/Requarks/wiki.git # Or download the project from release page...
$ npm install
$ npm run configure # Or something like this for config tasks...
```
And maybe the shell scripts just contain the above commands for simplicity.

Sincerely,
Emran

**Comment by NGPixel** [comment]
You're assuming everyone that will install the project is confortable with Node.js or git, which is simply not the case. The npm installation method is not the recommended one, as stated in the docs. It's there for legacy reasons. The recommended way is to use the simple, single line bash / powershell command.

As to why we don't use npm or the git clone you suggested:

- Cloning the repo means you download unnecessary dev files, requires you to have c++ compilation tools installed to build the project and requires a certain knowledge.
- Installing via npm introduces several issues, especially on systems where RAM is limited. Install will often freeze completely because of lack of RAM. Also, installing all the package via npm is extremely slow and unreliable.

The current method via bash / powershell is much better because:
- Only production files are fetched, no compilation required.
- Files and dependencies are fetched as a single zip, which is dramatically faster (a few seconds instead of 5-15 mins)
- It works on machines / containers with very low RAM.
- 0 issues related to installation since it was introduced, while the npm method was constantly having issues.

In the end, I don't see how running:
`curl -sSo- https://wiki.js.org/install.sh | bash`
is more complicated than:
`npm install wiki.js@latest`
for the end user...
