### ISSUE TITLE
Please ship 2.0

### ISSUE THREAD

**Issue by johnnyshields** [Requarks/wiki#597]
I strongly urge to focus all work on version 2.0 to stabilizing it and shipping a usable product. All modular storage etc. can wait, Postgres is good enough for 90% of users.

As I have repeatedly mentioned, the sooner we get a stable 2.0 the sooner we can get a critical mass of open-source contribution.

**Comment by NGPixel** [comment]
Adding MySQL, SQLite and MSSQL resulted in exactly 0 added development time. These are handled entirely by the underlying Knex.js ORM.

Modular storage is not something that can be patched on later. It's part of the core of wiki.js 2.0. You can't build a bridge and decide to work on the foundations later after the bridge is opened.

Like I previously said, 2.0 is a complete rewrite which means it will take time. It's not just some improvement work over 1.x that can be "stabilized".

Please stop creating these topics if they have nothing constructive to add beyond "ship sooner". The milestones listed in the project readme are considered critical and will be worked on for the 2.0 release. If you have questions or suggestions concerning these milestones, feel free to post them. However "ship sooner" doesn't automagically write code.

**Comment by virgil** [comment]
We love you @NGPixel.  And personally, I defer to your expert judgement.

**Comment by johnnyshields** [comment]
To be clear: "ship sooner" does not mean "write more code faster". It means "write less code and release limited-scope form what we already have." Version 2.0 was supposed to be stable 6 months ago, and people are still unable to make open source contributions on the 2.0 branch.

**Comment by johnnyshields** [comment]
And moreover, none of this is meant as a personal insult to you. I'm simply making my vote to democratize the ability to contribute code to this project, currently because no one can build/run v2.0 you are the sole contributor, which is not how OSS projects are meant to work. I'm all for you doing further experimental work on a v3 branch as long as we can get incremental improvements on v2.

**Comment by NGPixel** [comment]
This is simply not true. [This blog post](https://blog.requarks.io/2018/07/31/developers-wiki/) was posted over 3 weeks ago explaining how you can contribute. [Docs](https://docs.requarks.io/wiki/v/2.x/developers/getting-started) goes in detail how to install and run the project. There's extensive docs on [how to code new modules](https://docs.requarks.io/wiki/v/2.x/developers/modules/introduction). Following these instructions, you can install, run and develop for the project.

The issue you're referencing was a bug that was fixed the very same day. It definitely doesn't represent the current state of the project.

You can already contribute for storage and authentication modules. Rendering modules docs will go later this week, which will make 3 core areas where devs can contribute. I don't have analysts, solution architects and project managers who can plan the entire project and how every section should be designed. This means I have to create a clear framework of how modules works before opening the gates for other devs to contribute. Otherwise it will go in every direction and quickly become a mess.

This approach does take more time before other devs can contribute but I think it's completely worth it in the long run and makes for a more solid product.

**Comment by johnnyshields** [comment]
@NGPixel thanks for the explanation and your continued work.
