### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by Exselex** [Requarks/wiki#70]
How to deploy Wiki.js to Heroku?

**Comment by NGPixel** [comment]
An Heroku deploy button will be available in Beta 11, coming in the next days.

**Comment by NGPixel** [comment]
Heroku support added in Beta 12.

**Comment by xTNTx** [comment]
On Heroku dyno can be terminated at any time (due to a deploy or daily circling). Changes, that are saved locally but not pushed to remote, will be lost if termination happen earlier than regular re-sync. The app [should respond to SIGTERM](https://devcenter.heroku.com/articles/dynos#graceful-shutdown-with-sigterm) and run all jobs before exit. Let me know if you want this bug as a separate issue.

**Comment by NGPixel** [comment]
@xTNTx Good idea. Added graceful exit with git sync for Beta 12 (d744eb4d4c9a696bb7918857e3831b0adb9a2b5d)
