### ISSUE TITLE
[FEAT] Insert Image in Markdown editor

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#803]
Implement insert image functionality into the Markdown editor.

- [x] Upload new images
- [ ] Fetch remote image
- [x] Perform file manager operations like rename, move and delete
- [x] Support nested folders
- [ ] Add basic image editing capabilities
- [ ] Inline paste image

**Comment by col-panic** [comment]
I am currently evaluating a new wiki system and found yours - one of the greatest features here would be to be able to past clipboard images at the very point you're editing! This is a REAL time saver! We use it in redmine a lot (provided by this https://www.redmine.org/plugins/clipboard_image_paste plugin) Thanks

**Comment by eordano** [comment]
+1 This is a real game-changer

**Comment by AchimHentschel** [comment]
Pasting images has already been there for the 2.0 beta versions. At the moment, when taking a screenshot a long base64 encoded image is pasted into the markdown code. Unfortunately this moves the preview area to the right side of that encoded image string so no preview can be seen anymore. Would be great if these strings could be folded into a multi line representation. Alternatively the markdown panel could become horizontally scrollable so that the preview pane stays visible.

**Comment by NGPixel** [comment]
@AchimHentschel except that feature is still very much in early testing. The end goal is to upload them and replace with a normal resource link.

**Comment by AchimHentschel** [comment]
@NGPixel both ways are OK for me. But if the paste of base64 encoded images remains, please consider folding the encoding (multi line) for improved readability and preview.

**Comment by nilsmich** [comment]
It would be great to have the temporary fix for the problem with a horizontal scroll bar. Would be doable in about no time with css and be a huge improvement for the usability till the final feature is done. 

Thank you for the great system :)

**Comment by ralphgoebel** [comment]
Hi@NGPixel, first of all - I really love the work you are providing here! Will be our favorite Wiki for It documentation :) Thank you very much!

I am not a developer, but I agree to previous posts, that this feature would really be a time saver. We have some developers in our company. Do you have any idea of how much work is legt to do for this feature? Is there any other way I or we could support here, to get this feature (or others) running soon? :)

Kind regards

Ralph

**Comment by iksemot** [comment]
Hey @NGPixel !

Can you share with us have you done any progress with this feature? It would sooo good to paste pictures in the Markdown editor!

Tomasz

**Comment by yeuleh** [comment]
I'm looking forward to the feature(paste pictures), too.
Many modern markdown editors implemented this feature. It really helps a lot.

**Comment by arifeng** [comment]
Looking forward to this feature too ~

**Comment by TimoKruth** [comment]
Hey @NGPixel, I would like to contribute at this feature to your project as a start to maybe contribute at more points in the future. Would this be fine for you or should I start somewhere else? I would be personally motivated by this feature expecially the inline paste, thats why I came here first. Question would be are you working atm at this or would it be suited for me to work on without doubling the work done.
Alternativly I could offer help in reviewing some of the pull requests if that helps you more. I could in a first step comment if I could find any problems with the pull requests when I integrate them.
What do you think about this?

**Comment by NGPixel** [comment]
@TimoKruth Inline paste would be great. It's not under development atm no. Just keep in mind that Wiki.js 2.x is using CodeMirror 5 while 3.x will use CodeMirror 6, which is a total rewrite.

**Comment by naikymen** [comment]
Hi everyone, sorry to bump this old issue.

> Perform file manager operations like rename, move and delete

The item is ticked, but on version 2.5.298 the Move option is grayed out:

![image](https://github.com/requarks/wiki/assets/3259326/8b48dbcc-7c72-415a-9e41-a715aaa04ab6)

Our documentation is "modularized" by subdirectories, which means that having all images in a root directory is not compatible with our layout.

It would be great to be able to upload the images to a subdirectory directly, but since the "Move" action would solve our issue I wondered if there is a way to enable it.

Thanks for the great software :)

**Comment by NGPixel** [comment]
Closing in favor of #6544
