### ISSUE TITLE
arm 64 image build

### ISSUE THREAD

**Issue by Nox-404** [Requarks/wiki#815]
### Actual behavior

Wiki 2 doesn't start and we get this error:

`standard_init_linux.go:207: exec user process caused "exec format error"`

### Expected behavior

Wiki 2 to start

### Steps to reproduce the behavior

`docker run --rm -it requarks/wiki:beta` on `armv7l` (baremetal C1 on scaleway)

**Comment by chadweimer** [comment]
Came across this looking for arm32v7 (armhf) support. I am making the (potentially incorrect) assumption that the lack of it is the reason it's failing on scaleway, since arm64 would correspond to aarch. In my case, I'm interested in running on a Raspberry Pi.

**Comment by NGPixel** [comment]
Docker images for arm64 and armv7 are now available.

**Comment by thelazyanalyst** [comment]
Hello,

This bug is still present.

I followed the instructions to the letter here: https://docs.requarks.io/install/docker

**STR**
My commands on my RPI 3 B+ (arm64) Raspbian Buster:

> docker run -d -p 8080:3000 --name wikijs --restart unless-stopped -v ~/wikijsconfig.yml:/wiki/config.yml requarks/wiki:beta-arm64

This causes an infinite restart loop with the same error message about wrong arch:
standard_init_linux.go:211: exec user process caused "exec format error"
