### ISSUE TITLE
I see it requires MongoDB, can it use MongoDB instead of GIT?

### ISSUE THREAD

**Issue by vlos** [Requarks/wiki#9]
Basically would like to have a local DB if possible for repository rather than use GIT?
If yes, what do I need to do to configure it? thanks

**Comment by NGPixel** [comment]
You're confusing their purposes. MongoDB is for users, permissions, sessions, indexing, etc. basically administration stuff. Content (text, images, documents, etc) is stored as files on disk. Storing this type of content in Mongo wouldn't make much sense, especially performance wise. Git is merely a way to keep track of changes and sync/backup to a remote location (optional), it's not a storage solution. The storage solution is the file system.

That being said, you can disable the remote sync feature if it's bugging you:

```yaml
git: false
```

Git would still be used locally though. Git is already included on Linux systems and very easily installed on other platforms.

Just keep in mind that disabling the git sync means no backup. So make sure to schedule backups of your repository folder regularly.

Nick

**Comment by vlos** [comment]
Thanks for the info.

**Comment by Xirkolumi** [comment]
> Git would still be used locally though. Git is already included on Linux systems and very easily installed on other platforms.

if git sync is disabled I would expect it not to be used even locally.
@NGPixel Can you explain how is it used in such scenario?

**Comment by NGPixel** [comment]
Wiki.js was designed with Git in mind since the beginning. Adding the possibility to disable the remote sync was added much later as a request. If you disable the sync, Git is still being used to maintain the repository and changes are being tracked. The goal is to implement in the future an history feature where you can see who edited what, when and what changed, which requires Git.

Could Git be disabled completely? Sure. But considering it's built-in in Linux and a quick install with zero configuration on Windows, I prefer to leave it on for now.
