### ISSUE TITLE
Newline syntax regression (single newline produces html line break)

### ISSUE THREAD

**Issue by poikilos** [Requarks/wiki#957]
**Describe the bug**
A single newline produces an html newline but should not.

**To Reproduce**
1. Add a single newline inside of a paragraph.

**Expected behavior**
A single newline should be ignored, as per the markdown spec. Importing properly-formatted markdown from other platforms should work. Breaking the spec to please beginners by default is not a good practice.

**Screenshots**
N/A

**Host Info (please complete the following information):**
 - OS: unknown
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: SQLite

**Additional context**
Related to Issue #139

**Comment by NGPixel** [comment]
This is as designed, as this is the most commonly expected behavior (like GitHub), even though it does not match the official spec. This is why you'll be able to toggle the option in the admin area under Rendering > Markdown > Core. While the option is already there, it's not possible to save changes yet. It's coming in a future build.

**Comment by poikilos** [comment]
Thanks. I understand now that it is expected behavior even though it is not the spec. If we can figure out the config file option, I'll close.

**Comment by NGPixel** [comment]
Fixed by 3b347f262ce81732bacf3a51b2ecb98464a83130
